### ISSUE TITLE
ID Compressor Memes

### ISSUE THREAD

**Issue by crichards17** [crichards17/Distributed_Id_Allocator#60]
Memes required for team morale.

**Comment by crichards17** [comment]
@noencke please confirm if this can be completed this sprint or if it will need to be pushed.

**Comment by noencke** [comment]
![image](https://user-images.githubusercontent.com/78610362/222856024-4132da92-3973-4898-862e-d33799921ad9.png)

**Comment by noencke** [comment]
![image](https://user-images.githubusercontent.com/78610362/222856177-b4e70a70-959b-455b-ab57-054e73ddfe94.png)

**Comment by crichards17** [comment]
The day is saved.

**Comment by noencke** [comment]
![image](https://user-images.githubusercontent.com/78610362/222856320-7c3e0260-c1df-4314-bf4f-8a69466fbfc0.png)

**Comment by noencke** [comment]
![image](https://user-images.githubusercontent.com/78610362/222857013-f5332aa5-3c0b-4188-991f-9b759f4b5ea0.png)

**Comment by noencke** [comment]
![image](https://user-images.githubusercontent.com/78610362/222857486-4b0a2dfa-dfc4-4efd-b0c8-2336aaa33d90.png)

**Comment by noencke** [comment]
![image](https://user-images.githubusercontent.com/78610362/222859737-b090965b-de7c-47c9-9e23-7bb421f9e7e1.png)

**Comment by crichards17** [comment]
The day is ruined.

**Comment by crichards17** [comment]
That's... actually an encouragingly "fake expert" answer. Yay for us meat-brained monkeys.

**Comment by noencke** [comment]
![image](https://user-images.githubusercontent.com/78610362/222861020-cc62eb86-3f3d-4441-9ab2-6fbbf5e333ef.png)

**Comment by crichards17** [comment]
That one is disappointingly accurate.

**Comment by noencke** [comment]
Indeed. But it won't stop me from trying.

**Comment by crichards17** [comment]
Knuckles::punch_through_wasm_boundary(CoolnessEnum::RealCool);

**Comment by noencke** [comment]
![image](https://user-images.githubusercontent.com/78610362/222862403-70e5d571-4f5e-41e8-83be-b59b2edee031.png)

**Comment by noencke** [comment]
Runner ups:

![image](https://user-images.githubusercontent.com/78610362/222862658-f9c35645-96ba-47e0-b074-43708b2e56b6.png)
![image](https://user-images.githubusercontent.com/78610362/222862708-b25bc7c4-cd35-491e-baa3-f93d09308cd4.png)

**Comment by crichards17** [comment]
I like yours better.


![Image](https://user-images.githubusercontent.com/65925370/222863050-4ab4645a-4a44-4248-aa65-948ecaf06264.png)

**Comment by noencke** [comment]
Yours is "avant-garde". I'd like the NFT if it is available.

**Comment by crichards17** [comment]
Bid is currently sitting at 16 Wangas
