### ISSUE TITLE
Format TS code

### ISSUE THREAD

**Issue by taylorsw** [crichards17/Distributed_Id_Allocator#62]
We should get an auto-formatter going.

**Comment by crichards17** [comment]
How does that differ from linting?

**Comment by taylorsw** [comment]
Linting (like eslint) enforces coding rules (no any casts, etc.) and formatting enforces things like spacing and indenting.

**Comment by crichards17** [comment]
Do we not already have auto formatting? Or is that something you can
implement in the codebase rather than at the IDE level?

**Comment by taylorsw** [comment]
Added npm "prettier" and "prettier:fix" to the repo, could consider automating it as part of CI in the future.
