### ISSUE TITLE
Add initial cluster capacity param to Core constructor

### ISSUE THREAD

**Issue by crichards17** [crichards17/Distributed_Id_Allocator#66]
Core IdCompressor::new_with_session_id (also used by new() ) currently sets the cluster_capacity to a global "DEFAULT_CLUSTER_CAPACITY" in Persistence. We had added a note to refactor this to take a param for the initial cluster capacity.

Note that this will require a parallel change to deserialize() as well.

**Comment by crichards17** [comment]
@taylorsw I believe this was your note (I just came across the TODO today). Does this^^ sound correct?

**Comment by taylorsw** [comment]
Sounds good, except I don’t think deserialize needs to change at all (it shouldn't). It will already have a cluster capacity in the serialized state, and definitely shouldn't change it. Was there another way it was supposed to change?

**Comment by crichards17** [comment]
Just a reminder that deserialize calls compressor::new() is all.

**Comment by crichards17** [comment]
@taylorsw I'm looking at the FF implementation right now and it appears to work the way we currently have this implemented (set cluster capacity to Persistent default). Can you remind me what the reasoning here is for updating the constructor to require a cluster capacity param?

**Comment by taylorsw** [comment]
Actually, thinking about it more, I think @noencke and I decided to keep it that way to avoid accidentally changing a constant...but I also think they could accidentally change a constant they pass to set_cluster_capacity(...). Hmmm. I guess we can close this and revisit in the future.
